name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  schedule:
    # Run at 00:01 daily so it picks up any docs changes and updates the news stripe
    - cron: "01 0 * * *"

  workflow_dispatch:
    # For manual dispatch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: headlamp-k8s/headlamp
          path: headlamp
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          path: headlamp-website
          submodules: true

      - name: Make typedoc for Headlamp
        run: |
          cd headlamp
          make frontend-install
          make docs

      - name: Set HEADLAMP_DOCS environment variable
        run: |
          echo "HEADLAMP_DOCS=$(pwd)/headlamp/docs" >> $GITHUB_ENV

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BUSH_0475E2D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "headlamp-website/" # App source code path
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          HEADLAMP_DOCS: ${{ env.HEADLAMP_DOCS }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_BUSH_0475E2D03 }}
          action: "close"
